oncokb/curation-platform

app/index.html
Signed-off-by: Hongxin Zhang <hongxin@cbio.mskcc.org>
=> fix reference typo

app/scripts/controllers/tools.js
=> Add link for citations in excel

app/styles/main.scss, app/views/comments.html
fix https://github.com/oncokb/oncokb/issues/1672
=> Move comments.html css to main.scss

app/scripts/controllers/tools.js, app/views/tools.html
Fix https://github.com/oncokb/oncokb/issues/1671
1. remove useless checbox.
2. remove meta fields that curators doesn't need to know
=> Remove "_review" and "_uuid" fields in history

app/scripts/controllers/VariantCtrl.js, app/scripts/factories/VariantFactory.js, app/scripts/services/databaseconnector.js, app/views/variant.html
Switch to entrezGeneId when making the query
this solves https://github.com/oncokb/oncokb/issues/1690
=> Include all curated alterations as typeahead options in Variant Annotation

app/scripts/factories/VariantFactory.js
Signed-off-by: Hongxin Zhang <hongxin@cbio.mskcc.org>
=> remove unnecessary slash in the url

app/scripts/directives/realtimestring.js, app/views/gene.html, app/views/realtimeString.html
=> Fix checkbox auto unchecked issue

.editorconfig, app/scripts/app.js, app/scripts/controllers/gene.js, app/scripts/controllers/tools.js, app/scripts/directives/realtimestring.js, app/scripts/directives/reviewpanel.js, app/scripts/factories/VariantFactory.js, app/scripts/services/mainutils.js, app/styles/main.scss, app/views/gene.html, app/views/realtimeString.html, app/views/tools.html
1. Add solidPropagation and liquidPropagation for treatment and tools page.
2. Get rid of LEVEL_0 for therapy.
3. Refactor mainType and subtype since its api model changed.
4. Create Reviewed data in VariantFactory and refactor generateEvidences().
5. Add .editorconfig to format code.
=> Propagation 1.4

app/scripts/controllers/gene.js, app/scripts/directives/realtimestring.js, app/scripts/directives/reviewpanel.js, app/views/realtimeString.html
Update solid/liquid propagation in realtime
Save content data changes in review mode
=> Add pronostic_uuid and diagnostic_uuid for tumor_name_change

.editorconfig, app/scripts/app.js, app/scripts/controllers/gene.js, app/scripts/controllers/tools.js, app/scripts/directives/realtimestring.js, app/scripts/directives/reviewpanel.js, app/scripts/factories/VariantFactory.js, app/scripts/services/mainutils.js, app/styles/main.scss, app/views/gene.html, app/views/realtimeString.html, app/views/tools.html
- Create solid propagation and liquid propagation
- Get rid of level_0 and fix propagation.lastReviewed deleted issue
- Add solidPropagation and liquidPropagation for tools page
- Set default propagation to 'no' for special tumors like "All tumors"
=> Support solid/liquid propagation & Various changes

app/scripts/app.js, app/scripts/app.spec.js, app/scripts/controllers/gene.js, app/scripts/directives/realtimestring.js, app/scripts/factories/VariantFactory.js, app/scripts/services/databaseconnector.js, app/views/gene.html, app/views/realtimeString.html, package.json
Fix https://github.com/oncokb/oncokb/issues/1827
=> Remove evidence level 2B and change 2A to 2

app/scripts/factories/VariantFactory.js
Fixed the bug that cannot download data of Oncogene/Tumor Suppressor from Reviewed Data.
=> Check if item.gene is undefined

app/scripts/controllers/gene.js
Only open updated and added evidences in review mode when the changed evidences over 100.
=> Improve review mode performance.

app/scripts/controllers/gene.js
Signed-off-by: Hongxin Zhang <hongxin@cbio.mskcc.org>
=> Remove genestatus

app/scripts/controllers/tools.js, app/scripts/factories/VariantFactory.js, app/scripts/services/databaseconnector.js, app/scripts/services/mainutils.js, app/views/tools.html
=> Add data validation section in the Tools page

app/scripts/controllers/tools.js, app/scripts/services/databaseconnector.js, app/scripts/services/loadfiles.js, app/views/tools.html
=> Add data validation to check number of VUS

app/scripts/controllers/tools.js, app/styles/main.scss, app/views/tools.html
=> Seperate the data validation to different sections based on type

app/scripts/controllers/tools.js
We use tab as separator so we should use .txt as file extension.
=> Change file extension to .txt

app/scripts/directives/pubiframe.js, app/scripts/directives/qtip.js, app/views/pubIframe.html
Fix https://github.com/oncokb/oncokb/issues/1973
=> Fix iframe load failure issue

app/scripts/controllers/tools.js, app/scripts/factories/VariantFactory.js, app/scripts/services/databaseconnector.js, app/scripts/services/loadfiles.js, app/scripts/services/mainutils.js, app/styles/main.scss, app/views/tools.html
- Create a section to list all data validation issue in the Tools page
- Separate the data validation to different sections based on type(issue/info)
=> Enable user to validate the data in realtime

.github/release-drafter.yml, .github/workflows/release-management.yml
Add the release drafter similar to oncokb-core and oncokb-public
=> Include  Release Drafter

app/scripts/controllers/VariantCtrl.js, app/scripts/factories/VariantFactory.js, app/scripts/services/databaseconnector.js, app/scripts/services/mainutils.js, app/views/gene.html
This fixes https://github.com/oncokb/oncokb/issues/2148, https://github.com/oncokb/oncokb/issues/2149 and https://github.com/oncokb/oncokb/issues/2146
=> Update Create/Update/Release gene with grch38

app/scripts/controllers/gene.js
This fixes https://github.com/oncokb/oncokb/issues/2144 and https://github.com/oncokb/oncokb/issues/2143
=> Do not parse the display name in the frontend

app/index.html, app/scripts/controllers/gene.js, app/scripts/directives/qtip.js, app/scripts/directives/vusItem.js, app/views/drugs.html, app/views/evidencesReport.html, app/views/gene.html, app/views/pubIframe.html, app/views/vusItem.html
This fixes https://github.com/oncokb/oncokb/issues/2156
=> Turn VUS item to a directive and allow user to edit VUS

app/scripts/app.js, app/scripts/controllers/gene.js, app/scripts/services/databaseconnector.js
- Make sure the release gene dialog is closed
- Make sure showing the error message from the server
=> Fix issue when Release Gene failed

app/scripts/directives/qtip.js
This is related to https://github.com/oncokb/oncokb/issues/2189
=> Change the iframe source to pubtator

app/scripts/controllers/VariantCtrl.js, app/scripts/controllers/gene.js, app/scripts/controllers/tools.js, app/scripts/directives/curationQueue.js, app/scripts/directives/realtimestring.js, app/scripts/directives/tumorTypesDropdowns.js, app/scripts/factories/VariantFactory.js, app/scripts/filters/Filter.js, app/scripts/services/databaseconnector.js, app/scripts/services/mainutils.js, app/views/curationQueue.html, app/views/gene.html, app/views/modifyTumorTypes.html, app/views/tumorTypesDropdowns.html, app/views/variant.html
This fixes https://github.com/oncokb/oncokb/issues/2314
=> Allow curator to select relevant cancer type for Dx1

app/scripts/controllers/tools.js, app/scripts/factories/VariantFactory.js
The model has changed due to recent change
=> Fix cancer types issue in the Tools page

app/scripts/directives/addtherapy.js
We need to preserve the adding order
This fixes https://github.com/oncokb/oncokb/issues/2428
=> Do not sort drug when adding

app/scripts/controllers/gene.js
This is related to https://github.com/oncokb/oncokb/issues/2447
=> Add resistance

app/scripts/controllers/tools.js, app/views/tools.html
This fixes https://github.com/oncokb/oncokb/issues/2470
=> Add tool to generate review history difference note

app/scripts/controllers/tools.js, app/scripts/factories/VariantFactory.js, app/scripts/services/databaseconnector.js, app/views/tools.html
This fixes https://github.com/oncokb/oncokb/issues/2439
=> Add tool to Update gene transcript

app/scripts/controllers/gene.js, app/scripts/directives/realtimestring.js, app/scripts/factories/VariantFactory.js, app/scripts/services/databaseconnector.js, app/styles/main.scss, app/views/gene.html, app/views/modifyTumorTypes.html
- The relevant cancer types does not go through the review mode
- The relevant cancer types will be deleted right away if the level changes
- The relevant cancer types will be updated to production right away when it's specified
This fixes https://github.com/oncokb/oncokb/issues/2484
=> Allow exclude relevant cancer type for Tx/Px

app/scripts/controllers/gene.js, app/views/gene.html
This fixes https://github.com/oncokb/oncokb/issues/2514
=> Fix the issue that RCTs of dx/px summary is not updated when RCTs is updated

app/scripts/controllers/gene.js, app/views/gene.html
This fixes https://github.com/oncokb/oncokb/issues/2536
=> Allow choose relevant cancer types for the Tumor Type section

app/scripts/directives/createnewdrug.js, app/styles/main.scss, app/views/createNewDrug.html
We are using the new drug structure from oncokb-transcript
=> Update NCIT drug structure

app/scripts/app.spec.js, app/scripts/factories/VariantFactory.js
This fixes https://github.com/oncokb/oncokb/issues/3160
=> Add internalPublicApiLink so we can fetch the info endpoint through publicApiLink

app/scripts/app.spec.js, app/scripts/controllers/gene.js, app/scripts/controllers/gene.spec.js, app/scripts/directives/realtimestring.js, app/scripts/directives/reviewpanel.js, app/scripts/factories/VariantFactory.js, app/views/gene.html, app/views/realtimeString.html
This fixes https://github.com/oncokb/oncokb/issues/3091
=> Include FDA level

app/scripts/factories/VariantFactory.js, app/scripts/services/findregex.js
Clinical trial is not supported.
=> Remove trial validation

app/scripts/controllers/gene.js, app/scripts/directives/reviewpanel.js, app/scripts/services/mainutils.js, app/views/gene.html
- We should use the combination of cancerTypes uuid and excludedCancerTypes uuid in history tracking
- Only render reivew-panel when in review mode
=> Bug fixes related to cancer type updates

app/scripts/controllers/tools.js
This fixes https://github.com/oncokb/oncokb/issues/3246
=> Fix validation error when API fails

app/scripts/services/mainutils.js, app/views/tools.html
This is related to https://github.com/oncokb/oncokb/issues/3381
=> Update error message for creating gene

app/scripts/controllers/tools.js
This fixes https://github.com/oncokb/oncokb/issues/3325
=> Use markdown for diff note

app/scripts/controllers/gene.js
This is related to https://github.com/oncokb/oncokb/issues/3419
=> Trim all comments in mutation string

app/scripts/controllers/gene.js
- If a mutation is deleted from the mutation list and hasn't been reviewed,we allow curator adding the same mutation to VUS list. Upon rejecting the deletion, the mutation will also be removed from VUS list
- Update language when adding mutation into mutation list or VUS list when it's already in  the system
This fixes https://github.com/oncokb/oncokb/issues/3436
=> Allow adding same mutation into VUS list before reviewing
